Capstone Project:- Game dev conference
shubhambhoyar077/gdc_capstone pull request #1
Opened 2023-02-07 13:38 UTC by shubhambhoyar077

- Topic for this project is Game Developer Conference.
- Add support for both mobile and desktop screen.
- Create two pages <b>Home</b> and **About**.
- Create mobile menu using JavaScript.
- Create speakers section using JavaScript.
- Use <b>Lato</b> font.

2023-02-07 15:57 UTC, mckent05 requested changes
Hi @shubhambhoyar077, 

# STATUS: CHANGES REQUIRED ♻️ ♻️ 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![almost there](https://user-images.githubusercontent.com/73607512/207265056-d056ea78-77c5-4b66-802e-694a5ed4ecf3.gif)

## Highlights
- All linter checks are passing ✔️ ✔️ 
- Your PR is professional 👍 👍 


## Required Changes ♻️
**Note: I noticed you pushed some changes while I was making a review, please it is not advisable to do this as it can cause inconsistency in reviews, please ensure that all changes have been made before requesting a review and always ensure you wait until when a feedback is gotten before pushing more commits 🙏**
_Check the comments under the review._

## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-07 15:57 UTC, mckent05 commented on index.html
> +            </div>
**OPTIONAL** - It is not advisable to have two types of nav-links on your HTML page. I suggest you have just one link like you have above and use CSS to style it for both mobile and desktop versions. Please fix this 🙏

2023-02-07 15:57 UTC, mckent05 commented on index.html
> +                <h1 class="gdc">Game Developers Conference 2023</h1>
- To help improve the structure of your site, It is advisable that your `h` tag follows an ascending hierarchy i.e an `h2` tag comes after an `h1` tag, and an `h3` tag comes after an `h2` tag. Please fix this for all defaulting `hx` tags🙏

2023-02-07 15:57 UTC, mckent05 commented on index.html
> +        </section>
- Good job done so far, but there are some little differences between your project and what is in the design template for this section. Please pay attention to the marked sections in the image below and fix them 👍 

Your project:
-- The marked section should have a text instead of the image you have used, please fix it, and also for the about page too 😄 
-- Also, the text container are not entirely aligned in the middle, they are more aligned to the left than in the middle, please fix this 🙏 
<img width="958" alt="vvsdvsdv" src="https://user-images.githubusercontent.com/73607512/217291516-38d2e0de-78f9-4e87-902a-8c4772670351.PNG">

Figma template:
<img width="661" alt="eerverv" src="https://user-images.githubusercontent.com/73607512/217290839-617bc56c-809a-42ff-a487-3fd29a3be24b.PNG">

2023-02-07 15:57 UTC, mckent05 commented on index.html
> +        </section>
- This section of your page does not exactly look like what is in the design template. Remember it is important that you try to replicate the Figma design as closely as possible to give confidence to recruiters in your ability to produce exact business requirements 🙏.

Your project:
- Please ensure that all your cards are aligned in a row, please fix this 🙏 
<img width="929" alt="vEFwef" src="https://user-images.githubusercontent.com/73607512/217292201-d8a62cbf-a889-44eb-854d-5c5627025717.PNG">

Figma design:
<img width="608" alt="efwef" src="https://user-images.githubusercontent.com/73607512/217292328-f0ecf46e-d0ae-4a56-8af8-3783d0ceff26.PNG">

2023-02-07 15:57 UTC, mckent05 commented on about.html
> +        </footer>
- The footer section for the about page does not match what is in the design template. Please fix this 🙏 .Remember it is important that you try to replicate the Figma design as closely as possible to give confidence to recruiters in your ability to produce exact business requirements 🙏

Your project:
<img width="290" alt="cwcwc" src="https://user-images.githubusercontent.com/73607512/217293328-295ada4d-aaaa-41e2-bdbb-7544e2ef541b.PNG">

Design template:
Desktop version:
<img width="614" alt="vwvwv" src="https://user-images.githubusercontent.com/73607512/217293545-77a550a1-f1b6-4f49-82dc-03e94e2ecf3b.PNG">
Mobile version:
<img width="318" alt="wvavawv" src="https://user-images.githubusercontent.com/73607512/217293858-862045ea-3914-4ee2-8aa5-92f92120bf46.PNG">

2023-02-07 15:57 UTC, mckent05 commented on about.html
> +                </div>
- In the desktop version for this section i.e screen size `>765px`, the cards should be arranged horizontally in just one row. Please fix this, Remember it is important that you try to replicate the Figma design as closely as possible to give confidence to recruiters in your ability to produce exact business requirements 🙏

Your project:
<img width="399" alt="aeraer" src="https://user-images.githubusercontent.com/73607512/217294479-e66d1c82-ce81-4778-a2f0-862bac016642.PNG">

Design template:
<img width="530" alt="raeraerg" src="https://user-images.githubusercontent.com/73607512/217294661-ec479491-0cc1-4259-be6b-7b015a2907d0.PNG">

2023-02-07 16:12 UTC, shubhambhoyar077 commented on index.html
> +        </section>
Issue Fixed

2023-02-07 16:20 UTC, shubhambhoyar077 commented on about.html
> +                </div>
Fix layout issue

2023-02-07 16:30 UTC, shubhambhoyar077 commented on about.html
> +        </footer>
Followed given template and change color for footer in about page

2023-02-07 16:34 UTC, shubhambhoyar077 commented on index.html
> +                <h1 class="gdc">Game Developers Conference 2023</h1>
Fixed hx structure

2023-02-07 16:47 UTC, shubhambhoyar077 commented on index.html
> +            </div>
Hi @mckent05 
Please provide any hit or tutorial link for this **optional** part like how to approach this issue if possible.

2023-02-07 17:32 UTC, NahnahAJ approved these changes
## Project Status: APPROVED :green_circle: 

Hi @shubhambhoyar077 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media0.giphy.com/media/g9582DNuQppxC/giphy-downsized-medium.gif"/>

## Highlights
- [ ] Professional README file :heavy_check_mark: 
- [ ] Project well-deployed :heavy_check_mark: 
- [ ] No linter errors :heavy_check_mark: 
- [ ] Nice Design :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-07 17:32 UTC, NahnahAJ commented on index.html
> +            </div>
- [ OPTIONAL ] Great job making all the changes requested by the previous reviewer :muscle: 
- I will suggest that in your footer, you style the text so it looks shorter, concise, and readable when in the mobile view.  :100: Currently, it doesn't look so good. 
- Your Design
![image](https://user-images.githubusercontent.com/102699958/217317501-19df4914-e81a-4069-ac8a-9f875d4457c9.png)
- Behance Design
![image](https://user-images.githubusercontent.com/102699958/217317745-45166714-e6ff-4664-9857-69fee090748e.png)

2023-02-08 06:32 UTC, merged

2023-02-27 10:13 UTC, shubhambhoyar077 commented on about.html
> +                </div>
Fix Overflow issue in different branch.

2023-02-27 10:14 UTC, shubhambhoyar077 commented on index.html
> +            </div>
Fix text size issues in different branch.